---
- name: Install fileserver packages
  hosts: fileservers
  tasks:
    - name: Includes the variable
      include_vars: package.yml

    - name: Install the pacakge - epel-release
      include_tasks: install_package.yml
      vars:
        pacakges:
          web_pkg: epel-release

    - name: Installs the package -tomcat
      include_tasks: install_package.yml
      vars:
        pacakges:
          web_pkg: tomcat