---
- name: myvhost 역할 테스트
  gather_facts: yes
  hosts: webservers
  pre_tasks: 
  - debug: msg="==== webserver role start ===="

  roles:
  - myvhost

  post_tasks:
  - debug: msg="==== webserver role stop ===="

  